version: '3'


tasks:
  run:
    cmds:
      - go run ./cmd/main.go --config=./config/dev.yaml

  generate:
    aliases:
      - gen
    cmds:
      - protoc -I protos protos/proto/*.proto
        --go_out=./protos/gen
        --go-grpc_out=./protos/gen/




